In [1]:
import numpy as np
import pandas as pd

In [ ]:
# So basically pandas have two Object:
# 1. Dataframe
# 2. Series

In [2]:
# with one columns

In [3]:
pd.read_csv('D:\Machine Learning\Python Library\Pandas\subs.csv')

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_30504\554597312.py:1: SyntaxWarning: invalid escape sequence '\M'
  pd.read_csv('D:\Machine Learning\Python Library\Pandas\subs.csv')

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [7]:
#type
type(pd.read_csv('subs.csv')) #So it is basically storing the data in data frame order

pandas.core.frame.DataFrame

In [24]:
# So to convert it into Series 
# Use squeeze() parameter
subs = pd.read_csv('subs.csv').squeeze()
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [25]:
type(subs)

pandas.core.series.Series

In [ ]:
#with two columns
kohli = pd.read_csv('kohli_ipl.csv')# read the csv
kohli

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [ ]:
pd.read_csv('kohli_ipl.csv',index_col='match_no')# select the index

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [22]:
pd.read_csv('bollywood.csv')#read

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [23]:
#indexing
pd.read_csv('bollywood.csv',index_col='movie').squeeze()

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

Series Method

In [ ]:
#head and tail
subs.head() # it always give top 5 rows

0    48
1    57
2    40
3    43
4    44
Name: Subscribers gained, dtype: int64

In [ ]:
kohli.head(3) #first 3 match data

   match_no  runs
0         1     1
1         2    23
2         3    13