In [1]:
import numpy as np
import pandas as pd

In [ ]:
# So basically pandas have two Object:
# 1. Dataframe
# 2. Series

In [2]:
# with one columns

In [3]:
pd.read_csv('D:\Machine Learning\Python Library\Pandas\subs.csv')

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_30504\554597312.py:1: SyntaxWarning: invalid escape sequence '\M'
  pd.read_csv('D:\Machine Learning\Python Library\Pandas\subs.csv')

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [7]:
#type
type(pd.read_csv('subs.csv')) #So it is basically storing the data in data frame order

pandas.core.frame.DataFrame

In [ ]:
# So to convert it into Series 
# Use squeeze() parameter
s = pd.read_csv('subs.csv').squeeze()
s

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [15]:
type(s)

pandas.core.series.Series

In [18]:
#with two columns
kohli = pd.read_csv('kohli_ipl.csv')
kohli

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [19]:
pd.read_csv('kohli_ipl.csv',index_col='match_no')

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]