In [1]:
import numpy as np
import pandas as pd

Reading Of CSV File through Pandas

In [ ]:
# So basically pandas have two Object:
# 1. Dataframe
# 2. Series

In [2]:
# with one columns

In [3]:
pd.read_csv('D:\Machine Learning\Python Library\Pandas\subs.csv')

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_30504\554597312.py:1: SyntaxWarning: invalid escape sequence '\M'
  pd.read_csv('D:\Machine Learning\Python Library\Pandas\subs.csv')

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [7]:
#type
type(pd.read_csv('subs.csv')) #So it is basically storing the data in data frame order

pandas.core.frame.DataFrame

In [24]:
# So to convert it into Series 
# Use squeeze() parameter
subs = pd.read_csv('subs.csv').squeeze()
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [25]:
type(subs)

pandas.core.series.Series

In [48]:
#with two columns
pd.read_csv('kohli_ipl.csv').squeeze()# read the csv

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [49]:
kohli=pd.read_csv('kohli_ipl.csv',index_col='match_no')# select the index
kohli

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [22]:
pd.read_csv('bollywood.csv')#read

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [31]:
#indexing
movies =pd.read_csv('bollywood.csv',index_col='movie').squeeze()
movies

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

Series Method :

1. head Function

In [ ]:
#head
subs.head() # it always give top 5 rows

0    48
1    57
2    40
3    43
4    44
Name: Subscribers gained, dtype: int64

In [ ]:
kohli.head(3) #first 3 match data

   match_no  runs
0         1     1
1         2    23
2         3    13

2. Tail function

In [ ]:
#tail
kohli.tail(10) #last 10 match data

     match_no  runs
205       206     0
206       207     0
207       208     9
208       209    58
209       210    30
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

3. Sample Function

In [32]:
#sample
# it shows randomly any one movie from a list of 1500 movie 
movies.sample()

movie
Ajji    Sushama Deshpande
Name: lead, dtype: object

In [33]:
# Any 5 random movies 
movies.sample(5)

movie
Inteha (2003 film)            Ashmit Patel
Bioscopewala               Danny Denzongpa
Andaaz                        Akshay Kumar
Dhokha                     Muzamil Ibrahim
Tanu Weds Manu: Returns     Kangana Ranaut
Name: lead, dtype: object

4. Values Counts OR Frequency Count Function

In [35]:
#values_count -> movie
movies.value_counts()

lead
Akshay Kumar            48
Amitabh Bachchan        45
Ajay Devgn              38
Salman Khan             31
Sanjay Dutt             26
                        ..
Tanishaa Mukerji         1
Tanuja                   1
Ankit                    1
Rakhee Gulzar            1
Geetika Vidya Ohlyan     1
Name: count, Length: 566, dtype: int64

In [70]:
vk = pd.read_csv('kohli_ipl.csv',index_col='runs').squeeze()# series
vk

runs
1       1
23      2
13      3
12      4
1       5
     ...
0     211
20    212
73    213
25    214
7     215
Name: match_no, Length: 215, dtype: int64

In [71]:
# sort_values -> inplace (Only works for series)
# vk = pd.read_csv('kohli_ipl.csv')['runs']
vk.sort_values()
#ascending order

runs
1       1
23      2
13      3
12      4
1       5
     ...
0     211
20    212
73    213
25    214
7     215
Name: match_no, Length: 215, dtype: int64

In [72]:
kohli.sort_values(by='runs',ascending=True)  #ascending order

          runs
match_no
8            0
87           0
93           0
91           0
206          0
...        ...
164        100
120        100
123        108
126        109
128        113

[215 rows x 1 columns]

In [52]:
kohli.sort_values(by='runs', ascending=False)

          runs
match_no
128        113
126        109
123        108
120        100
164        100
...        ...
93           0
130          0
206          0
207          0
211          0

[215 rows x 1 columns]

In [ ]:
kohli.sort_values(by='runs', ascending=False).head(1).values[0]

array([113])

In [ ]:
# Above sorting are temporary changes

In [ ]:
# But if u want to make permanent changes use this method to sort permanently

5. Inpace Sorting

In [67]:
vk = vk.sort_values()
vk = vk.copy()
vk.sort_values(inplace=True)

In [ ]:
vk #Already Sorted

7        0
86       0
92       0
90       0
205      0
      ...
163    100
119    100
122    108
125    109
127    113
Name: runs, Length: 215, dtype: int64

6. Sort Index

In [74]:
movies.sort_index(inplace=True)
movies

movie
1920 (film)                   Rajniesh Duggall
1920: London                     Sharman Joshi
1920: The Evil Returns             Vicky Ahuja
1971 (2007 film)                Manoj Bajpayee
2 States (2014 film)              Arjun Kapoor
                                   ...
Zindagi 50-50                      Veena Malik
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi Tere Naam           Mithun Chakraborty
Zokkomon                       Darsheel Safary
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Name: lead, Length: 1500, dtype: object

In [75]:
vk.sort_index(inplace=True)
vk

runs
0        8
0       87
0       93
0       91
0      206
      ...
100    164
100    120
108    123
109    126
113    128
Name: match_no, Length: 215, dtype: int64

In [ ]:
vk.sort_index(ascending=False,inplace=True) #inplace and ascending
vk

runs
113    128
109    126
108    123
100    164
100    120
      ...
0       91
0       93
0       87
0      211
0        8
Name: match_no, Length: 215, dtype: int64