In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('../dataSets/imdb-top-1000.csv')
movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [ ]:
genres = movies.groupby('Genre')
genres.first()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [ ]:
genres.apply(min)# minimum

Genre
Action       Director
Adventure    Director
Animation    Director
Biography    Director
Comedy       Director
Crime        Director
Drama        Director
Family       Director
Fantasy      Director
Film-Noir    Director
Horror       Director
Mystery      Director
Thriller     Director
Western      Director
dtype: str

QUESTION

In [7]:
#find the number of movies starting with A for each group
def foo(group):
    print(type(group))
    print(group)
    return group

In [8]:
genres.apply(foo)

<class 'pandas.DataFrame'>
                                          Series_Title Released_Year  Runtime  \
2                                      The Dark Knight          2008      152
5        The Lord of the Rings: The Return of the King          2003      201
8                                            Inception          2010      148
10   The Lord of the Rings: The Fellowship of the Ring          2001      178
13               The Lord of the Rings: The Two Towers          2002      179
..                                                 ...           ...      ...
968                                       Falling Down          1993      113
979                                      Lethal Weapon          1987      109
982                                          Mad Max 2          1981       96
983                                       The Warriors          1979       92
985                               Escape from Alcatraz          1979      112

     IMDB_Rating           Director              Star1  No_of_Votes  \
2            9.0  Christopher Nolan     Christian Bale      2303232
5            8.9      Peter Jackson        Elijah Wood      1642758
8            8.8  Christopher Nolan  Leonardo DiCaprio      2067042
10           8.8      Peter Jackson        Elijah Wood      1661481
13           8.7      Peter Jackson        Elijah Wood      1485555
..           ...                ...                ...          ...
968          7.6    Joel Schumacher    Michael Douglas       171640
979          7.6     Richard Donner         Mel Gibson       236894
982          7.6      George Miller         Mel Gibson       166588
983          7.6        Walter Hill       Michael Beck        93878
985          7.6         Don Siegel     Clint Eastwood       121731

           Gross  Metascore
2    534858444.0       84.0
5    377845905.0       94.0
8    292576195.0       74.0
10   315544750.0       92.0
13   342551365.0       87.0
..           ...        ...
968   40903593.0       56.0
979   65207127.0       68.0
982   12465371.0       77.0
983   22490039.0       65.0
985   43000000.0       76.0

[172 rows x 9 columns]
<class 'pandas.DataFrame'>
                       Series_Title Released_Year  Runtime  IMDB_Rating  \
21                     Interstellar          2014      169          8.6
47               Back to the Future          1985      116          8.5
93             Inglourious Basterds          2009      153          8.3
110                        Das Boot          1981      149          8.3
114           2001: A Space Odyssey          1968      149          8.3
..                              ...           ...      ...          ...
957  Fear and Loathing in Las Vegas          1998      118          7.6
964                        Dead Man          1995      121          7.6
966                       Apollo 13            PG      140          7.6
984                The Muppet Movie          1979       95          7.6
991                  Kelly's Heroes          1970      144          7.6

              Director                Star1  No_of_Votes        Gross  \
21   Christopher Nolan  Matthew McConaughey      1512360  188020017.0
47     Robert Zemeckis       Michael J. Fox      1058081  210609762.0
93   Quentin Tarantino            Brad Pitt      1267869  120540719.0
110  Wolfgang Petersen      Jürgen Prochnow       231855   11487676.0
114    Stanley Kubrick          Keir Dullea       603517   56954992.0
..                 ...                  ...          ...          ...
957      Terry Gilliam          Johnny Depp       259753   10680275.0
964       Jim Jarmusch          Johnny Depp        90442    1037847.0
966         Ron Howard            Tom Hanks       269197  173837933.0
984      James Frawley           Jim Henson        32802   76657000.0
991    Brian G. Hutton       Clint Eastwood        45338    1378435.0

     Metascore
21        74.0
47        87.0
93        69.0
110       86.0
114       84.0
..         ...
957       41.0
964       62.0
966       77.0
984       74.0
991       50.0

[72 rows x 9 columns]
<class 'pandas.DataFrame'>
                          Series_Title Released_Year  Runtime  IMDB_Rating  \
23       Sen to Chihiro no kamikakushi          2001      125          8.6
43                       The Lion King          1994       88          8.5
46                      Hotaru no haka          1988       89          8.5
56                      Kimi no na wa.          2016      106          8.4
58   Spider-Man: Into the Spider-Verse          2018      117          8.4
..                                 ...           ...      ...          ...
956                              Mulan          1998       88          7.6
971                  Omohide poro poro          1991      118          7.6
976                 The Little Mermaid          1989       83          7.6
986                     Watership Down          1978       91          7.6
992                    The Jungle Book          1967       78          7.6

                Director             Star1  No_of_Votes        Gross  \
23        Hayao Miyazaki     Daveigh Chase       651376   10055859.0
43          Roger Allers       Rob Minkoff       942045  422783777.0
46         Isao Takahata   Tsutomu Tatsumi       235231  150734678.0
56        Makoto Shinkai  Ryûnosuke Kamiki       194838    5017246.0
58       Bob Persichetti      Peter Ramsey       375110  190241310.0
..                   ...               ...          ...          ...
956        Tony Bancroft        Barry Cook       256906  120620254.0
971        Isao Takahata         Miki Imai        27071     453243.0
976         Ron Clements       John Musker       237696  111543479.0
986         Martin Rosen       John Hubley        33656  232841485.0
992  Wolfgang Reitherman       Phil Harris       166409  141843612.0

     Metascore
23        96.0
43        88.0
46        94.0
56        79.0
58        87.0
..         ...
956       71.0
971       90.0
976       88.0
986       64.0
992       65.0

[82 rows x 9 columns]
<class 'pandas.DataFrame'>
          Series_Title Released_Year  Runtime  IMDB_Rating          Director  \
7     Schindler's List          1993      195          8.9  Steven Spielberg
15          Goodfellas          1990      146          8.7   Martin Scorsese
18            Hamilton          2020      160          8.6       Thomas Kail
35    The Intouchables          2011      112          8.5   Olivier Nakache
38         The Pianist          2002      150          8.5    Roman Polanski
..                 ...           ...      ...          ...               ...
923     La Vie En Rose          2007      140          7.6     Olivier Dahan
940  Finding Neverland          2004      106          7.6      Marc Forster
949               Blow          2001      124          7.6         Ted Demme
952      The Hurricane          1999      146          7.6    Norman Jewison
987   Midnight Express          1978      121          7.6       Alan Parker

                  Star1  No_of_Votes        Gross  Metascore
7           Liam Neeson      1213505   96898818.0       94.0
15       Robert De Niro      1020727   46836394.0       90.0
18   Lin-Manuel Miranda        55291  440984783.0       90.0
35        Éric Toledano       760360   13182281.0       57.0
38         Adrien Brody       729603   32572577.0       85.0
..                  ...          ...          ...        ...
923    Marion Cotillard        82781   10301706.0       66.0
940         Johnny Depp       198677   51680613.0       67.0
949         Johnny Depp       240714   52990775.0       52.0
952   Denzel Washington        91557   50668906.0       74.0
987          Brad Davis        73662   35000000.0       59.0

[88 rows x 9 columns]
<class 'pandas.DataFrame'>
                                       Series_Title Released_Year  Runtime  \
19                                     Gisaengchung          2019      132
26                                  La vita è bella          1997      116
51                                     Modern Times          1936       87
52                                      City Lights          1931       87
64                                         3 Idiots          2009      170
..                                              ...           ...      ...
977  The Naked Gun: From the Files of Police Squad!          1988       85
978                    Planes, Trains & Automobiles          1987       93
989                                The Long Goodbye          1973      112
994                              A Hard Day's Night          1964       87
995                          Breakfast at Tiffany's          1961      115

     IMDB_Rating         Director            Star1  No_of_Votes        Gross  \
19           8.6     Bong Joon Ho     Kang-ho Song       552778   53367844.0
26           8.6  Roberto Benigni  Roberto Benigni       623629   57598247.0
51           8.5  Charles Chaplin  Charles Chaplin       217881     163245.0
52           8.5  Charles Chaplin  Charles Chaplin       167839      19181.0
64           8.4  Rajkumar Hirani       Aamir Khan       344445    6532908.0
..           ...              ...              ...          ...          ...
977          7.6     David Zucker   Leslie Nielsen       152871   78756177.0
978          7.6      John Hughes     Steve Martin       124773   49530280.0
989          7.6    Robert Altman    Elliott Gould        26337     959000.0
994          7.6   Richard Lester      John Lennon        40351   13780024.0
995          7.6    Blake Edwards   Audrey Hepburn       166544  679874270.0

     Metascore
19        96.0
26        59.0
51        96.0
52        99.0
64        67.0
..         ...
977       76.0
978       72.0
989       87.0
994       96.0
995       76.0

[155 rows x 9 columns]
<class 'pandas.DataFrame'>
                Series_Title Released_Year  Runtime  IMDB_Rating  \
1              The Godfather          1972      175          9.2
3     The Godfather: Part II          1974      202          9.0
4               12 Angry Men          1957       96          9.0
6               Pulp Fiction          1994      154          8.9
22            Cidade de Deus          2002      130          8.6
..                       ...           ...      ...          ...
958              Funny Games          1997      108          7.6
960                 Sleepers          1996      147          7.6
974  The Godfather: Part III          1990      162          7.6
980             Blood Simple          1984       99          7.6
999             The 39 Steps          1935       86          7.6

                 Director           Star1  No_of_Votes        Gross  Metascore
1    Francis Ford Coppola   Marlon Brando      1620367  134966411.0      100.0
3    Francis Ford Coppola       Al Pacino      1129952   57300000.0       90.0
4            Sidney Lumet     Henry Fonda       689845    4360000.0       96.0
6       Quentin Tarantino   John Travolta      1826188  107928762.0       94.0
22     Fernando Meirelles      Kátia Lund       699256    7563397.0       79.0
..                    ...             ...          ...          ...        ...
958        Michael Haneke  Susanne Lothar        65058  217345863.0       69.0
960        Barry Levinson  Robert De Niro       186734   49100000.0       49.0
974  Francis Ford Coppola       Al Pacino       359809   66666062.0       60.0
980             Joel Coen      Ethan Coen        87745    2150000.0       82.0
999      Alfred Hitchcock    Robert Donat        51853  302787539.0       93.0

[107 rows x 9 columns]
<class 'pandas.DataFrame'>
                        Series_Title Released_Year  Runtime  IMDB_Rating  \
0           The Shawshank Redemption          1994      142          9.3
9                         Fight Club          1999      139          8.8
11                      Forrest Gump          1994      142          8.8
17   One Flew Over the Cuckoo's Nest          1975      133          8.7
20                   Soorarai Pottru          2020      153          8.6
..                               ...           ...      ...          ...
990                     Giù la testa          1971      157          7.6
993                           Blowup          1966      111          7.6
996                            Giant          1956      201          7.6
997            From Here to Eternity          1953      118          7.6
998                         Lifeboat          1944       97          7.6

                   Director              Star1  No_of_Votes        Gross  \
0            Frank Darabont        Tim Robbins      2343110   28341469.0
9             David Fincher          Brad Pitt      1854740   37030102.0
11          Robert Zemeckis          Tom Hanks      1809221  330252182.0
17             Milos Forman     Jack Nicholson       918088  112000000.0
20            Sudha Kongara             Suriya        54995  556832648.0
..                      ...                ...          ...          ...
990            Sergio Leone        Rod Steiger        30144     696690.0
993  Michelangelo Antonioni     David Hemmings        56513  632532802.0
996          George Stevens   Elizabeth Taylor        34075  195217415.0
997          Fred Zinnemann     Burt Lancaster        43374   30500000.0
998        Alfred Hitchcock  Tallulah Bankhead        26471  852142728.0

     Metascore
0         80.0
9         66.0
11        82.0
17        83.0
20         NaN
..         ...
990       77.0
993       82.0
996       84.0
997       85.0
998       78.0

[289 rows x 9 columns]
<class 'pandas.DataFrame'>
                            Series_Title Released_Year  Runtime  IMDB_Rating  \
688           E.T. the Extra-Terrestrial          1982      115          7.8
698  Willy Wonka & the Chocolate Factory          1971      100          7.8

             Director         Star1  No_of_Votes        Gross  Metascore
688  Steven Spielberg  Henry Thomas       372490  435110554.0       91.0
698        Mel Stuart   Gene Wilder       178731    4000000.0       67.0
<class 'pandas.DataFrame'>
                     Series_Title Released_Year  Runtime  IMDB_Rating  \
321  Das Cabinet des Dr. Caligari          1920       76          8.1
568                     Nosferatu          1922       94          7.9

         Director          Star1  No_of_Votes        Gross  Metascore
321  Robert Wiene  Werner Krauss        57428  337574718.0        NaN
568   F.W. Murnau    Max Schreck        88794  445151978.0        NaN
<class 'pandas.DataFrame'>
           Series_Title Released_Year  Runtime  IMDB_Rating          Director  \
309       The Third Man          1949      104          8.1        Carol Reed
456  The Maltese Falcon          1941      100          8.0       John Huston
712   Shadow of a Doubt          1943      108          7.8  Alfred Hitchcock

               Star1  No_of_Votes        Gross  Metascore
309     Orson Welles       158731     449191.0       97.0
456  Humphrey Bogart       148928    2108060.0       96.0
712    Teresa Wright        59556  123353292.0       94.0
<class 'pandas.DataFrame'>
                 Series_Title Released_Year  Runtime  IMDB_Rating  \
49                     Psycho          1960      109          8.5
75                      Alien          1979      117          8.4
271                 The Thing          1982      109          8.1
419              The Exorcist          1973      122          8.0
544  Night of the Living Dead          1968       96          7.9
707             The Innocents          1961      100          7.8
724                   Get Out          2017      104          7.7
844                 Halloween          1978       91          7.7
876         The Invisible Man          1933       71          7.7
932                       Saw          2004      103          7.6
948                The Others          2001      101          7.6

               Director             Star1  No_of_Votes        Gross  Metascore
49     Alfred Hitchcock   Anthony Perkins       604211   32000000.0       97.0
75         Ridley Scott  Sigourney Weaver       787806   78900000.0       89.0
271      John Carpenter      Kurt Russell       371271   13782838.0       57.0
419    William Friedkin     Ellen Burstyn       362393  232906145.0       81.0
544    George A. Romero       Duane Jones       116557      89029.0       89.0
707        Jack Clayton      Deborah Kerr        27007    2616000.0       88.0
724        Jordan Peele    Daniel Kaluuya       492851  176040665.0       85.0
844      John Carpenter  Donald Pleasence       233106   47000000.0       87.0
876         James Whale      Claude Rains        30683  298791505.0       87.0
932           James Wan        Cary Elwes       379020   56000369.0       46.0
948  Alejandro Amenábar     Nicole Kidman       337651   96522687.0       74.0
<class 'pandas.DataFrame'>
          Series_Title Released_Year  Runtime  IMDB_Rating  \
69             Memento          2000      113          8.4
81         Rear Window          1954      112          8.4
119            Vertigo          1958      128          8.3
145     Shutter Island          2010      138          8.2
220            Kahaani          2012      122          8.1
393     Twelve Monkeys          1995      129          8.0
420             Sleuth          1972      138          8.0
714  The Lady Vanishes          1938       96          7.8
829          Spoorloos          1988      107          7.7
899          El cuerpo          2012      112          7.6
959          Dark City          1998      100          7.6
961       Lost Highway          1997      134          7.6

                 Director                     Star1  No_of_Votes        Gross  \
69      Christopher Nolan                Guy Pearce      1125712   25544867.0
81       Alfred Hitchcock             James Stewart       444074   36764313.0
119      Alfred Hitchcock             James Stewart       364368    3200000.0
145       Martin Scorsese         Leonardo DiCaprio      1129894  128012934.0
220           Sujoy Ghosh               Vidya Balan        57806    1035953.0
393         Terry Gilliam              Bruce Willis       578443   57141459.0
420  Joseph L. Mankiewicz          Laurence Olivier        44748    4081254.0
714      Alfred Hitchcock         Margaret Lockwood        47400  474203697.0
829        George Sluizer  Bernard-Pierre Donnadieu        33982  367916835.0
899           Oriol Paulo             Jose Coronado        57549  140340673.0
959           Alex Proyas              Rufus Sewell       187927   14378331.0
961           David Lynch              Bill Pullman       131101    3796699.0

     Metascore
69        80.0
81       100.0
119      100.0
145       63.0
220        NaN
393       74.0
420        NaN
714       98.0
829        NaN
899        NaN
959       66.0
961       52.0
<class 'pandas.DataFrame'>
        Series_Title Released_Year  Runtime  IMDB_Rating       Director  \
700  Wait Until Dark          1967      108          7.8  Terence Young

              Star1  No_of_Votes       Gross  Metascore
700  Audrey Hepburn        27733  17550741.0       81.0
<class 'pandas.DataFrame'>
                        Series_Title Released_Year  Runtime  IMDB_Rating  \
12   Il buono, il brutto, il cattivo          1966      161          8.8
48      Once Upon a Time in the West          1968      165          8.5
115       Per qualche dollaro in più          1965      132          8.3
691           The Outlaw Josey Wales          1976      135          7.8

           Director           Star1  No_of_Votes       Gross  Metascore
12     Sergio Leone  Clint Eastwood       688390   6100000.0       90.0
48     Sergio Leone     Henry Fonda       302844   5321508.0       80.0
115    Sergio Leone  Clint Eastwood       232772  15000000.0       74.0
691  Clint Eastwood  Clint Eastwood        65659  31800000.0       69.0

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime  IMDB_Rating           Director              Star1  \
Genre
Action   2        152          9.0  Christopher Nolan     Christian Bale
         5        201          8.9      Peter Jackson        Elijah Wood
         8        148          8.8  Christopher Nolan  Leonardo DiCaprio
         10       178          8.8      Peter Jackson        Elijah Wood
         13       179          8.7      Peter Jackson        Elijah Wood
...               ...          ...                ...                ...
Thriller 700      108          7.8      Terence Young     Audrey Hepburn
Western  12       161          8.8       Sergio Leone     Clint Eastwood
         48       165          8.5       Sergio Leone        Henry Fonda
         115      132          8.3       Sergio Leone     Clint Eastwood
         691      135          7.8     Clint Eastwood     Clint Eastwood

              No_of_Votes        Gross  Metascore
Genre
Action   2        2303232  534858444.0       84.0
         5        1642758  377845905.0       94.0
         8        2067042  292576195.0       74.0
         10       1661481  315544750.0       92.0
         13       1485555  342551365.0       87.0
...                   ...          ...        ...
Thriller 700        27733   17550741.0       81.0
Western  12        688390    6100000.0       90.0
         48        302844    5321508.0       80.0
         115       232772   15000000.0       74.0
         691        65659   31800000.0       69.0

[1000 rows x 9 columns]

In [16]:
def Newfoo(group):
    return group['Series_Title'].str.startswith('A').sum()

genres.apply(Newfoo)

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
dtype: int64

In [17]:
#ranking of each movie oin the basis of imdb score
def rank_movie(group):
    group['genre_rank'] = group['IMDB_Rating'].rank(ascending=False)
    return group

In [18]:
genres.apply(rank_movie)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime  IMDB_Rating           Director              Star1  \
Genre
Action   2        152          9.0  Christopher Nolan     Christian Bale
         5        201          8.9      Peter Jackson        Elijah Wood
         8        148          8.8  Christopher Nolan  Leonardo DiCaprio
         10       178          8.8      Peter Jackson        Elijah Wood
         13       179          8.7      Peter Jackson        Elijah Wood
...               ...          ...                ...                ...
Thriller 700      108          7.8      Terence Young     Audrey Hepburn
Western  12       161          8.8       Sergio Leone     Clint Eastwood
         48       165          8.5       Sergio Leone        Henry Fonda
         115      132          8.3       Sergio Leone     Clint Eastwood
         691      135          7.8     Clint Eastwood     Clint Eastwood

              No_of_Votes        Gross  Metascore  genre_rank
Genre
Action   2        2303232  534858444.0       84.0         1.0
         5        1642758  377845905.0       94.0         2.0
         8        2067042  292576195.0       74.0         3.5
         10       1661481  315544750.0       92.0         3.5
         13       1485555  342551365.0       87.0         6.0
...                   ...          ...        ...         ...
Thriller 700        27733   17550741.0       81.0         1.0
Western  12        688390    6100000.0       90.0         1.0
         48        302844    5321508.0       80.0         2.0
         115       232772   15000000.0       74.0         3.0
         691        65659   31800000.0       69.0         4.0

[1000 rows x 10 columns]

In [21]:
#find normalised IMDB rating group wise
def normal(group):
    group['norm_rating'] = (group['IMDB_Rating'] - group['IMDB_Rating'].min())/(group['IMDB_Rating'].max()-group['IMDB_Rating'].min())
    return  group

genres.apply(normal)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime  IMDB_Rating           Director              Star1  \
Genre
Action   2        152          9.0  Christopher Nolan     Christian Bale
         5        201          8.9      Peter Jackson        Elijah Wood
         8        148          8.8  Christopher Nolan  Leonardo DiCaprio
         10       178          8.8      Peter Jackson        Elijah Wood
         13       179          8.7      Peter Jackson        Elijah Wood
...               ...          ...                ...                ...
Thriller 700      108          7.8      Terence Young     Audrey Hepburn
Western  12       161          8.8       Sergio Leone     Clint Eastwood
         48       165          8.5       Sergio Leone        Henry Fonda
         115      132          8.3       Sergio Leone     Clint Eastwood
         691      135          7.8     Clint Eastwood     Clint Eastwood

              No_of_Votes        Gross  Metascore  norm_rating
Genre
Action   2        2303232  534858444.0       84.0     1.000000
         5        1642758  377845905.0       94.0     0.928571
         8        2067042  292576195.0       74.0     0.857143
         10       1661481  315544750.0       92.0     0.857143
         13       1485555  342551365.0       87.0     0.785714
...                   ...          ...        ...          ...
Thriller 700        27733   17550741.0       81.0          NaN
Western  12        688390    6100000.0       90.0     1.000000
         48        302844    5321508.0       80.0     0.700000
         115       232772   15000000.0       74.0     0.500000
         691        65659   31800000.0       69.0     0.000000

[1000 rows x 10 columns]