In [1]:
import numpy as np
import pandas as pd

In [4]:
multiindex = pd.MultiIndex.from_product(
    [
        ['CSE', 'ECE', 'ME', 'CE'],   # Branches
        ['2023', '2024']              # Years
    ],
    names=['branch', 'year']
)

branch_df1 = pd.DataFrame(
    [
        [1, 2],
        [3, 4],
        [5, 6],
        [7, 8],
        [9, 10],
        [11, 12],
        [13, 14],
        [15, 16]
    ],
    index=multiindex,
    columns=['avg_package', 'students']
)
branch_df1

             avg_package  students
branch year
CSE    2023            1         2
       2024            3         4
ECE    2023            5         6
       2024            7         8
ME     2023            9        10
       2024           11        12
CE     2023           13        14
       2024           15        16

In [6]:
branch_df1.loc['CSE']

      avg_package  students
year
2023            1         2
2024            3         4

In [ ]:
branch_df1['avg_package']#multiindex series

branch  year
CSE     2023     1
        2024     3
ECE     2023     5
        2024     7
ME      2023     9
        2024    11
CE      2023    13
        2024    15
Name: avg_package, dtype: int64

In [ ]:
branch_df1['students']#multiindex series

branch  year
CSE     2023     2
        2024     4
ECE     2023     6
        2024     8
ME      2023    10
        2024    12
CE      2023    14
        2024    16
Name: students, dtype: int64

STACK AND UNSTACK

In [10]:
branch_df1.unstack()

       avg_package      students
year          2023 2024     2023 2024
branch
CE              13   15       14   16
CSE              1    3        2    4
ECE              5    7        6    8
ME               9   11       10   12

In [11]:
branch_df1.unstack().unstack()

             year  branch
avg_package  2023  CE        13
                   CSE        1
                   ECE        5
                   ME         9
             2024  CE        15
                   CSE        3
                   ECE        7
                   ME        11
students     2023  CE        14
                   CSE        2
                   ECE        6
                   ME        10
             2024  CE        16
                   CSE        4
                   ECE        8
                   ME        12
dtype: int64

In [8]:

branch_df1 = pd.DataFrame(
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ],
    columns=["A", "B"]
)

In [11]:
branch_df1

   A  B
0  1  2
1  3  4
2  5  6

In [12]:
branch_df1.unstack()

A  0    1
   1    3
   2    5
B  0    2
   1    4
   2    6
dtype: int64

In [14]:
branch_df1.stack().to_frame()

     0
0 A  1
  B  2
1 A  3
  B  4
2 A  5
  B  6

In [15]:
branch_df1.unstack()

A  0    1
   1    3
   2    5
B  0    2
   1    4
   2    6
dtype: int64

In [16]:
branch_df1.unstack().unstack()

   0  1  2
A  1  3  5
B  2  4  6