In [16]:
import numpy as np
import pandas as pd

In [17]:
batsman = pd.read_csv('../dataSets/batsman_runs_ipl.csv')
batsman

             batter  batsman_run
0    A Ashish Reddy          280
1          A Badoni          161
2        A Chandila            4
3          A Chopra           53
4       A Choudhary           25
..              ...          ...
600      Yash Dayal            0
601   Yashpal Singh           47
602     Younis Khan            3
603    Yuvraj Singh         2754
604          Z Khan          117

[605 rows x 2 columns]

In [18]:
batsman['batting_rank'] = batsman['batsman_run'].rank(ascending=False)
batsman.sort_values('batting_rank')

             batter  batsman_run  batting_rank
569         V Kohli         6634           1.0
462        S Dhawan         6244           2.0
130       DA Warner         5883           3.0
430       RG Sharma         5881           4.0
493        SK Raina         5536           5.0
..              ...          ...           ...
570  V Pratap Singh            0         594.0
63     Abdur Razzak            0         594.0
562          U Kaul            0         594.0
65       Akash Deep            0         594.0
57           AS Roy            0         594.0

[605 rows x 3 columns]

In [19]:
# setIndex(dataFrame) ->inplace
batsman.set_index('batter')#so now batter is acting like  current index

                batsman_run  batting_rank
batter
A Ashish Reddy          280         166.5
A Badoni                161         226.0
A Chandila                4         535.0
A Chopra                 53         329.0
A Choudhary              25         402.5
...                     ...           ...
Yash Dayal                0         594.0
Yashpal Singh            47         343.0
Younis Khan               3         547.5
Yuvraj Singh           2754          27.0
Z Khan                  117         256.0

[605 rows x 2 columns]

In [20]:
# To make it permanent change
batsman.set_index('batter',inplace=True)

In [ ]:
batsman #changes saved permanantly.

                batsman_run  batting_rank
batter
A Ashish Reddy          280         166.5
A Badoni                161         226.0
A Chandila                4         535.0
A Chopra                 53         329.0
A Choudhary              25         402.5
...                     ...           ...
Yash Dayal                0         594.0
Yashpal Singh            47         343.0
Younis Khan               3         547.5
Yuvraj Singh           2754          27.0
Z Khan                  117         256.0

[605 rows x 2 columns]