In [1]:
import numpy as np
import pandas as pd

In [14]:
marks={
    'maths':67,
    'english':57,
    'science':89,
    'hindi':100
}
marks_series = pd.Series(marks)
marks_series

maths       67
english     57
science     89
hindi      100
dtype: int64

In [2]:
batsman = pd.read_csv('../dataSets/batsman_runs_ipl.csv')
batsman

             batter  batsman_run
0    A Ashish Reddy          280
1          A Badoni          161
2        A Chandila            4
3          A Chopra           53
4       A Choudhary           25
..              ...          ...
600      Yash Dayal            0
601   Yashpal Singh           47
602     Younis Khan            3
603    Yuvraj Singh         2754
604          Z Khan          117

[605 rows x 2 columns]

In [3]:
batsman['batting_rank'] = batsman['batsman_run'].rank(ascending=False)
batsman.sort_values('batting_rank')

             batter  batsman_run  batting_rank
569         V Kohli         6634           1.0
462        S Dhawan         6244           2.0
130       DA Warner         5883           3.0
430       RG Sharma         5881           4.0
493        SK Raina         5536           5.0
..              ...          ...           ...
570  V Pratap Singh            0         594.0
63     Abdur Razzak            0         594.0
562          U Kaul            0         594.0
65       Akash Deep            0         594.0
57           AS Roy            0         594.0

[605 rows x 3 columns]

In [4]:
# To make it permanent change
batsman.set_index('batter',inplace=True)

In [8]:
batsman.reset_index()# it comes to it's previous state .

     index          batter  batsman_run  batting_rank
0        0  A Ashish Reddy          280         166.5
1        1        A Badoni          161         226.0
2        2      A Chandila            4         535.0
3        3        A Chopra           53         329.0
4        4     A Choudhary           25         402.5
..     ...             ...          ...           ...
600    600      Yash Dayal            0         594.0
601    601   Yashpal Singh           47         343.0
602    602     Younis Khan            3         547.5
603    603    Yuvraj Singh         2754          27.0
604    604          Z Khan          117         256.0

[605 rows x 4 columns]

In [6]:
batsman.reset_index(inplace=True)# it comes to it's previous state .

In [7]:
batsman

             batter  batsman_run  batting_rank
0    A Ashish Reddy          280         166.5
1          A Badoni          161         226.0
2        A Chandila            4         535.0
3          A Chopra           53         329.0
4       A Choudhary           25         402.5
..              ...          ...           ...
600      Yash Dayal            0         594.0
601   Yashpal Singh           47         343.0
602     Younis Khan            3         547.5
603    Yuvraj Singh         2754          27.0
604          Z Khan          117         256.0

[605 rows x 3 columns]

QUESTIONS

In [ ]:
#how to replace the existing index without loosing

In [10]:
batsman.reset_index().set_index('batting_rank')

              index          batter  batsman_run
batting_rank
166.5             0  A Ashish Reddy          280
226.0             1        A Badoni          161
535.0             2      A Chandila            4
329.0             3        A Chopra           53
402.5             4     A Choudhary           25
...             ...             ...          ...
594.0           600      Yash Dayal            0
343.0           601   Yashpal Singh           47
547.5           602     Younis Khan            3
27.0            603    Yuvraj Singh         2754
256.0           604          Z Khan          117

[605 rows x 3 columns]

In [ ]:
#series to dataFrame using restIndex
print(type(marks_series))
print(type(marks_series.reset_index()))
#So basically resetIndex converts a series into a DataFrame

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>