In [1]:
import numpy as np
import pandas as pd

In [2]:


students = pd.DataFrame({
    'name':['nitish','ankit','rupesh',np.nan,'mrityunjay',np.nan,'rishabh',np.nan,'aditya',np.nan],
    'college':['bit','iit','vit',np.nan,np.nan,'vlsi','ssit',np.nan,np.nan,'git'],
    'branch':['eee','it','cse',np.nan,'me','ce','civ','cse','bio',np.nan],
    'cgpa':[6.66,8.25,6.41,np.nan,5.6,9.0,7.4,10,7.4,np.nan],
    'package':[4,5,6,np.nan,6,7,8,9,np.nan,np.nan]
})

students

         name college branch   cgpa  package
0      nitish     bit    eee   6.66      4.0
1       ankit     iit     it   8.25      5.0
2      rupesh     vit    cse   6.41      6.0
3         NaN     NaN    NaN    NaN      NaN
4  mrityunjay     NaN     me   5.60      6.0
5         NaN    vlsi     ce   9.00      7.0
6     rishabh    ssit    civ   7.40      8.0
7         NaN     NaN    cse  10.00      9.0
8      aditya     NaN    bio   7.40      NaN
9         NaN     git    NaN    NaN      NaN

In [3]:
#isnull[series -> dataframe]
students['name'].isnull

<bound method Series.isnull of 0        nitish
1         ankit
2        rupesh
3           NaN
4    mrityunjay
5           NaN
6       rishabh
7           NaN
8        aditya
9           NaN
Name: name, dtype: object>

In [6]:
#notnull(series + dataframe)
students['name'][students['name'].notnull()]

0        nitish
1         ankit
2        rupesh
4    mrityunjay
6       rishabh
8        aditya
Name: name, dtype: object

In [7]:
#to find whether there is any missing valuews or not
students['name'].hasnans

True

In [8]:
students

         name college branch   cgpa  package
0      nitish     bit    eee   6.66      4.0
1       ankit     iit     it   8.25      5.0
2      rupesh     vit    cse   6.41      6.0
3         NaN     NaN    NaN    NaN      NaN
4  mrityunjay     NaN     me   5.60      6.0
5         NaN    vlsi     ce   9.00      7.0
6     rishabh    ssit    civ   7.40      8.0
7         NaN     NaN    cse  10.00      9.0
8      aditya     NaN    bio   7.40      NaN
9         NaN     git    NaN    NaN      NaN

In [9]:
students.isnull()

    name  college  branch   cgpa  package
0  False    False   False  False    False
1  False    False   False  False    False
2  False    False   False  False    False
3   True     True    True   True     True
4  False     True   False  False    False
5   True    False   False  False    False
6  False    False   False  False    False
7   True     True   False  False    False
8  False     True   False  False     True
9   True    False    True   True     True

In [ ]:
students.notnull()#opposite of isnull

    name  college  branch   cgpa  package
0   True     True    True   True     True
1   True     True    True   True     True
2   True     True    True   True     True
3  False    False   False  False    False
4   True    False    True   True     True
5  False     True    True   True     True
6   True     True    True   True     True
7  False    False    True   True     True
8   True    False    True   True    False
9  False     True   False  False    False