In [1]:
import numpy as np
import pandas as pd

In [2]:
temp = pd.Series([10,2,3,10,45,78,10])

In [3]:
temp.drop(index=[0,6])

1     2
2     3
3    10
4    45
5    78
dtype: int64

In [4]:


students = pd.DataFrame({
    'name':['nitish','ankit','rupesh',np.nan,'mrityunjay',np.nan,'rishabh',np.nan,'aditya',np.nan],
    'college':['bit','iit','vit',np.nan,np.nan,'vlsi','ssit',np.nan,np.nan,'git'],
    'branch':['eee','it','cse',np.nan,'me','ce','civ','cse','bio',np.nan],
    'cgpa':[6.66,8.25,6.41,np.nan,5.6,9.0,7.4,10,7.4,np.nan],
    'package':[4,5,6,np.nan,6,7,8,9,np.nan,np.nan]
})

students

         name college branch   cgpa  package
0      nitish     bit    eee   6.66      4.0
1       ankit     iit     it   8.25      5.0
2      rupesh     vit    cse   6.41      6.0
3         NaN     NaN    NaN    NaN      NaN
4  mrityunjay     NaN     me   5.60      6.0
5         NaN    vlsi     ce   9.00      7.0
6     rishabh    ssit    civ   7.40      8.0
7         NaN     NaN    cse  10.00      9.0
8      aditya     NaN    bio   7.40      NaN
9         NaN     git    NaN    NaN      NaN

In [ ]:
students.drop(columns=['branch','cgpa']) # delete columns

         name college  package
0      nitish     bit      4.0
1       ankit     iit      5.0
2      rupesh     vit      6.0
3         NaN     NaN      NaN
4  mrityunjay     NaN      6.0
5         NaN    vlsi      7.0
6     rishabh    ssit      8.0
7         NaN     NaN      9.0
8      aditya     NaN      NaN
9         NaN     git      NaN

In [6]:
students.drop(index=[0,8])

         name college branch   cgpa  package
1       ankit     iit     it   8.25      5.0
2      rupesh     vit    cse   6.41      6.0
3         NaN     NaN    NaN    NaN      NaN
4  mrityunjay     NaN     me   5.60      6.0
5         NaN    vlsi     ce   9.00      7.0
6     rishabh    ssit    civ   7.40      8.0
7         NaN     NaN    cse  10.00      9.0
9         NaN     git    NaN    NaN      NaN

In [7]:
students.set_index('name').drop(index=['rupesh','ankit'])

           college branch   cgpa  package
name
nitish         bit    eee   6.66      4.0
NaN            NaN    NaN    NaN      NaN
mrityunjay     NaN     me   5.60      6.0
NaN           vlsi     ce   9.00      7.0
rishabh       ssit    civ   7.40      8.0
NaN            NaN    cse  10.00      9.0
aditya         NaN    bio   7.40      NaN
NaN            git    NaN    NaN      NaN