In [1]:
import numpy as np
import pandas as pd

In [2]:
courses = pd.read_csv('../dataSets/courses.csv')
student  = pd.read_csv('../dataSets/students.csv')
november = pd.read_csv('../dataSets/reg-month1.csv')
december = pd.read_csv('../dataSets/reg-month2.csv')
matches = pd.read_csv('../dataSets/matches.csv')
delivery = pd.read_csv('../dataSets/deliveries.csv')

In [3]:
regs = pd.concat([november,december],ignore_index=True)
regs

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3
25           3          5
26          16          7
27          12         10
28          12          1
29          14          9
30           7          7
31           7          2
32          16          3
33          17         10
34          11          8
35          14          6
36          12          5
37          12          7
38          18          8
39           1         10
40           1          9
41           2          5
42           7          6
43          22          5
44          22          6
45          23          9
46          23          5
47          14          4
48          14          1
49          11         10
50          42          9
51          50          8
52          38          1

OUTER JOINS

In [4]:
student.merge(regs,how='outer',on='student_id')

    student_id                name  partner  course_id
0            1       Kailash Harjo     23.0        1.0
1            1       Kailash Harjo     23.0        6.0
2            1       Kailash Harjo     23.0       10.0
3            1       Kailash Harjo     23.0        9.0
4            2         Esha Butala      1.0        5.0
5            3      Parveen Bhalla      3.0        3.0
6            3      Parveen Bhalla      3.0        5.0
7            4         Marlo Dugal     14.0        NaN
8            5         Kusum Bahri      6.0        NaN
9            6  Lakshmi Contractor     10.0        NaN
10           7        Tarun Thaker      9.0        8.0
11           7        Tarun Thaker      9.0       10.0
12           7        Tarun Thaker      9.0        7.0
13           7        Tarun Thaker      9.0        2.0
14           7        Tarun Thaker      9.0        6.0
15           8      Radheshyam Dey      5.0        NaN
16           9   Nitika Chatterjee      4.0        NaN
17          10      Aayushman Sant      8.0        NaN
18          11  David Mukhopadhyay     20.0        7.0
19          11  David Mukhopadhyay     20.0        8.0
20          11  David Mukhopadhyay     20.0       10.0
21          12          Radha Dutt     19.0       10.0
22          12          Radha Dutt     19.0        1.0
23          12          Radha Dutt     19.0        5.0
24          12          Radha Dutt     19.0        7.0
25          13      Munni Varghese     24.0        3.0
26          14    Pranab Natarajan     22.0        9.0
27          14    Pranab Natarajan     22.0        6.0
28          14    Pranab Natarajan     22.0        4.0
29          14    Pranab Natarajan     22.0        1.0
30          15           Preet Sha     16.0        5.0
31          15           Preet Sha     16.0        1.0
32          16        Elias Dodiya     25.0        9.0
33          16        Elias Dodiya     25.0        5.0
34          16        Elias Dodiya     25.0        7.0
35          16        Elias Dodiya     25.0        3.0
36          17        Yasmin Palan      7.0        7.0
37          17        Yasmin Palan      7.0       10.0
38          18     Fardeen Mahabir     13.0        6.0
39          18     Fardeen Mahabir     13.0        1.0
40          18     Fardeen Mahabir     13.0        8.0
41          19        Qabeel Raman     12.0        4.0
42          19        Qabeel Raman     12.0        2.0
43          20       Hanuman Hegde     11.0        NaN
44          21          Seema Kota     15.0        1.0
45          22          Yash Sethi     21.0        3.0
46          22          Yash Sethi     21.0        5.0
47          22          Yash Sethi     21.0        6.0
48          23      Chhavi Lachman     18.0        1.0
49          23      Chhavi Lachman     18.0        4.0
50          23      Chhavi Lachman     18.0        3.0
51          23      Chhavi Lachman     18.0        6.0
52          23      Chhavi Lachman     18.0        9.0
53          23      Chhavi Lachman     18.0        5.0
54          24        Radhika Suri     17.0        4.0
55          25     Shashank D’Alia      2.0        1.0
56          25     Shashank D’Alia      2.0       10.0
57          38                 NaN      NaN        1.0
58          42                 NaN      NaN        9.0
59          50                 NaN      NaN        8.0

LAST 10 ROWS

In [5]:
student.merge(regs,how='outer',on='student_id').tail(10)

    student_id             name  partner  course_id
50          23   Chhavi Lachman     18.0        3.0
51          23   Chhavi Lachman     18.0        6.0
52          23   Chhavi Lachman     18.0        9.0
53          23   Chhavi Lachman     18.0        5.0
54          24     Radhika Suri     17.0        4.0
55          25  Shashank D’Alia      2.0        1.0
56          25  Shashank D’Alia      2.0       10.0
57          38              NaN      NaN        1.0
58          42              NaN      NaN        9.0
59          50              NaN      NaN        8.0